blog/urls.py
from django.urls import path
from . import views

# URLパターンをサカ引きできるように名前をつける
app_name = 'blog'

# URLを登録するための変数

urlpatterns = [
    # リクエストされたURLのページへのフルパス部分が’’（無し）にマッチングした場合
    # ViewsモジュールのIndexViewクラスをインスタンス化する
    path('',views.IndexView.as_view(),name='index'),

    # リクエストされたURLが「blog-detail/レコードのid」の場合は
    # BlogDetailを実行
    path(#詳細ページのURLは「blog-detail/レコードのid/」
        'blog-detail/<int:pk>/',
        #viewsモジュールのBlogDetailを実行
        views.BlogDetail.as_view(),
        # URLパターンの名前を’blog_detail'にする
        name='blog_detail'
        ),

    # scienceカテゴリの一覧ページのURLパターン
    path(
        # sicenceカテゴリの一覧ページのURLは「science-list」
        'science-list/',
        # viewsモジュールのScienceViewを実行
        views.ScienceView.as_view(),
        # URLパターンの名前を'science_list'にする
        name='science_list'
    ),

    # dailylifeカテゴリの一覧ページのURLパターン
    path(
        # dailylifeカテゴリの一覧ページのURLは「dailylife-list」
        'dailylife-list/',
        # viewsモジュールのDailylifeViewを実行
        views.DailylifeView.as_view(),
        # URLパターンの名前を'dailylife_list'にする
        name='dailylife_list'
    ),

    # musicカテゴリの一覧ページのURLパターン
    path(
        # musicカテゴリの一覧ページのURLは「music-list」
        'music_list/',
        # viewsモジュールのMusicViewを実行
        views.MusicView.as_view(),
        # URLパターンの名前を'music_list'にする
        name='music_list'
    ),

    # 問い合わせページのURLパターン
    path(
        # 問い合わせページのURLは「contact/」
        'contact/',
        # viewsモジュールのContactViewを実行
        views.ContactView.as_view(),
        # URLパターンの名前を'contact'にする
        name='contact'
    )
]

firstproject/urls.py
from django.contrib import admin
from django.urls import path,include    # includeを追加

urlpatterns = [
    path('admin/', admin.site.urls),

    # https://（ホスト名）/以下のURLパターンにblogアプリの
    # URLconf(urls.py)を含める
    path('',include('blog.urls'))
]

photoProject/photoProject/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),

    # photo.urlsへのURLパターンを追加
    path('',include('photo.urls')),
]

blog/models.py
from django.db import models

# Create your models here.

class BlogPost(models.Model):
    '''モデルクラス
    '''
    # カテゴリに設定する項目を入れ子のタプルとして定義
    # 最初の要素はモデルが使用する値、2番目の要素は選択メニューに表示する文字列
    CATEGORY = (('science','科学のこと'),('dailylife','日常のこと'),('music','音楽のこと'))

    # タイトル用のフィールド
    title = models.CharField(
        verbose_name='タイトル',    #フィールドのタイトル
        max_length=200             #最大文字数は200
    )

    #本文用のフィールド
    content = models.TextField(
        verbose_name='本文'         #フィールドのタイトル
    )

    #投稿日時のフィールド
    posted_at = models.DateTimeField(
        verbose_name='投稿日時',     #フィールドのタイトル
        auto_now_add=True           #日時を自動追加
    )

    #カテゴリのフィールド
    category = models.CharField(
        verbose_name='カテゴリ',    #フィールドのタイトル
        max_length=50,             #最大文字数は50
        choices=CATEGORY
    )

    def __str__(self):
        '''オブジェクトを文字列に変換して返す

        Returns(str):投稿記事のタイトル
        '''
        return self.title

blog/forms.py
# django.formsをインポート
from django import forms
# django.core.mailモジュールからEmailMessageをインポート
from django.core.mail import EmailMessage

class ContactForm(forms.Form):
    # フォームのフィールドの中身をクラス変数として定義
    name = forms.CharField(label="お名前")
    email = forms.EmailField(label="メールアドレス")
    title = forms.CharField(label="件名")
    message = forms.CharField(label="メッセージ",widget=forms.Textarea)

    def __init__ (self,*args,**kwargs):
        '''ContactFormのコンストラクター
        
            フィールドの初期化を行う
        '''
        super().__init__(*args,**kwargs)

        # nameフィールドのplaceholderにメッセージを登録
        self.fields['name'].widget.attrs['placeholder'] = 'お名前を入力してください'
        # nameフィールドを出力する<input>タグのclass属性を設定
        self.fields['name'].widget.attrs['class'] = 'form-control'
        # emailフィールドのplaceholderにメッセージを登録
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスを入力してください'
        # emailフィールドを出力する<input>タグのclass属性を設定
        self.fields['email'].widget.attrs['class'] = 'form-control'
        # titteフィールドのplaceholderにメッセージを登録
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルを入力してください'
        # titleフィールドを出力する<input>タグのclass属性を設定
        self.fields['title'].widget.attrs['class'] = 'form-control'
        # messageフィールドのplaceholderにメッセージを登録
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージを入力してください'
        # messageフィールドを出力する<input>タグのclass属性を設定
        self.fields['message'].widget.attrs['class'] = 'form-control'

    def send_email(self):
        '''フォームに入力された内容をメールで送信する
        
        '''
        # フォームに入力されたデータを、フィールド名を指定して取得
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        # メールのタイトルの書式を設定
        subject = f'お問い合わせ:{title}'
        # フォームの入力データの書式を設定
        message = (
            f'送信者名:{name}\n'
            f'メールアドレス:{email}\n'
            f'タイトル:{title}\n'
            f'メッセージ:\n{message}'
        )
        # メールの送信元のアドレス
        from_email = 'rs.philuna@gmail.com'
        # 送信先のメールアドレス
        to_list = ['rs.philuna@gmail.com']
        # EmailMessageオブジェクトを生成
        email_message = EmailMessage(
                            subject=subject,
                            body=message,
                            from_email = from_email,
                            to=to_list
                            )
        # EmailMessageクラスのsend()でメールサーバーからメールを送信
        email_message.send()

blog/views.py
from django.shortcuts import render

# django.views.genericからListView、DetailViewをインポート
from django.views.generic import ListView,DetailView
#モデルBlogPostをインポート
from .models import BlogPost
# django.views.genericからFormViewをインポート
from django.views.generic import FormView
# django.urlsからrevers_lazyをインポート
from django.urls import reverse_lazy
# formsモジュールからContactFormをインポート
from .forms import ContactForm
# django.contribからmessagesをインポート
from django.contrib import messages
class IndexView(ListView):
    '''トップページのビュー
    
    投稿記事を一覧表示するのでListViewを継承する
    
    Attributes:
    template_name:レンダリングするテンプレート
    context_object_name:object_listキーの別名を設定
    queryset:データベースのクエリ
    '''

    # index.htmlをレンダリングする
    template_name = 'index.html'
    #object_listキーの別名を設定
    context_object_name = 'orderby_records'
    #モデルBlogPostのオブジェクトにorder_by()を適用して
    #BlogPostのレコードを投稿日時の降順で並べ替える
    queryset = BlogPost.objects.order_by('-posted_at')
    # 1ページに表示するレコード数
    paginate_by = 2

class BlogDetail(DetailView):
    '''詳細ページのビュー
    
    投稿記事の詳細を表示するのでDetailViewを継承する
    Attributes:
        template_name:レンダリングするテンプレート
        Model:モデルのクラス
    '''
    # post.htmlをレンダリングする
    template_name = 'post.html'
    # クラス変数modelにモデルBlogPostを設定
    model = BlogPost
    
class ScienceView(ListView):
    '''scienc_listページのビュー

    '''
    # science.htmlをレンダリングする
    template_name = 'science_list.html'
    #object_listキーの別名を設定
    context_object_name = 'science_records'
    #モデルBlogPostのオブジェクトにorder_by()を適用して
    #BlogPostのレコードを投稿日時の降順で並べ替える
    queryset = BlogPost.objects.filter(category='science').order_by('-posted_at')
    # 1ページに表示するレコード数
    paginate_by = 2
    
class DailylifeView(ListView):
    '''dailylife_listページのビュー

    '''
    # sailylife_list.htmlをレンダリングする
    template_name = 'dailylife_list.html'
    #object_listキーの別名を設定
    context_object_name = 'dailylife_records'
    #モデルBlogPostのオブジェクトにorder_by()を適用して
    #BlogPostのレコードを投稿日時の降順で並べ替える
    queryset = BlogPost.objects.filter(category='dailylife').order_by('-posted_at')
    # 1ページに表示するレコード数
    paginate_by = 2

class MusicView(ListView):
    '''music_listページのビュー

    '''
    # music_list.htmlをレンダリングする
    template_name = 'music_list.html'
    #object_listキーの別名を設定
    context_object_name = 'music_records'
    #モデルBlogPostのオブジェクトにorder_by()を適用して
    #BlogPostのレコードを投稿日時の降順で並べ替える
    queryset = BlogPost.objects.filter(category='music').order_by('-posted_at')
    # 1ページに表示するレコード数
    paginate_by = 2


class ContactView(FormView):
    '''問い合わせページを一覧表示するビュー
    
    '''
    # contact.htmlをレンダリングする
    template_name = 'contact.html'
    # クラス変数form_classにforms.pyで定義したConractFormを設定
    form_class = ContactForm
    # 送信完了後にリダイレクトするページ
    success_url = reverse_lazy('blog:contact')

    def form_valid(self, form):
        '''FormViewクラスのform_valid()をオーバーライド
        フォームのバリデーションを通過したデータがPOSTされた時に呼ばれる
        メール送信を行う
        
        parameters:
            form(django.forms.Form):
                form_classに格納されているフォームのオブジェクト
        Return:
            HttpResponseRedirectのオブジェクト
            オブジェクトをインスタンス化するとsuccess_urlで
            設定されているURLにリダイレクトされる
        '''
        # forms.pyのsend_email()を実行してメール送信を行う
        form.send_email()
        # 送信完了後に表示するメッセージ
        messages.success(
            self.request,'お問い合わせは正常に送信されました。'
        )
        # 戻り値はスーパークラスのform_valid()の戻り値（HttpResponseRedirect)
        return super().form_valid(form)

blog/templates/base.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする -->
{% load static %}
<!DOCTYPE html>
<!-- 言語設定をenからjaに変更 -->
<html lang="ja">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <!-- ページタイトル -->
    <title>Django's Blog</title>
    <!-- ページタイトル横に表示されるアイコン-->
    <!-- staticでfabicon.icoのURLを生成する -->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <!-- ナビゲーションバーの左上のアンカーテキストとhref属性の値を変更 -->
            <a class="navbar-brand" href="{% url 'blog:index' %}">Django's Blog</a>
            <button class="navbar-toggler" 
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarResponsive"
                    aria-controls="navbarResponsive"
                    aria-expanded="false"
                    aria-label="Toggle navigation">Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <!-- ナビゲーションメニューの「HOME」のhref属性の値を変更 -->
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:index' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:science_list' %}">SCIENCE</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:dailylife_list' %}">DAILYLIFE</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:music_list' %}">MUSIC</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:contact' %}">CONTACT</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page Header-->
    <!-- ページのヘッダーはベーステンプレートを使用するページで設定する -->
    {% block header %}{% endblock %}
    <!-- Main Content-->
    <!-- ページのコンテンツはベーステンプレートを使用するページで設定する -->
    {% block contents %}{% endblock %}
    <!-- Footer-->
    <footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <!-- Twitterアイコンの<a>タグのhref属性にURLを設定 -->
                            <a href="https://twitter.com/">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <!-- Facebookアイコンの<a>タグのhref属性にURLを設定 -->
                            <a href="https://www.facebook.com/">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <!-- GitHubアイコンの<a>タグのhref属性にURLを設定 -->
                            <a href="https://github.co.jp/">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <!-- 著作権の記載を独自のものに変更 -->
                    <div class="small text-center text-muted fst-italic">Copyright &copy; Django's Blog 2024</div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

blog/templates/dailylife_list.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!-- 静的ファイルのURLを生成するstaticha
個々のページで読み込むことが必要-->
{% load static %}

<!-- ヘッダー情報のページタイトルは
ベーステンプレートを利用するページで設定する-->
{% block title %}Django's Blog - Dailylife{% endblock %}


<!-- Page Header-->
{% block header %}
<!-- ページヘッダーを設定（ドキュメントの構造に合わせてインデント） -->
<!-- ベーステンプレートを利用するページで設定する -->
<header class="masthead" style="background-image: url('{% static 'assets/img/home-bg.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <!-- ヘッダーの大見出し（タイトル）を変更 -->
                    <h1>Django's Blog</h1>
                    <!-- サブタイトルを変更 -->
                    <span class="subheading">Dailylifeカテゴリの記事一覧</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

<!-- Main Content-->
{% block contents %}
<!-- ページのコンテンツを設定（ドキュメントの構造に合わせてインデント） -->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- 
            Dailylifeレコードが格納されたDailylife_recordsから
            レコードを1件ずつrecordに取り出す
            -->
            {% for record in dailylife_records %}
            <!-- Post preview-->
            <div class="post-preview">
                <!--
                urlでURLパターン'blog-detail/記事のid/'を生成し、
                詳細尾エージへのリンクを設定
                -->
                <a href="{% url 'blog:blog_detail' record.pk %}">
                    <!-- 記事のタイトル -->
                    <h2 class="post-title">
                        <!-- titleフィールドを出力 -->
                        {{record.title}}
                    </h2>
                    <!-- 投稿記事本文 -->
                    <h3 class="post-subtitle">
                        <!-- サブタイトルの文字サイズを16ptにする -->
                        <span style="font-size: 16pt;">

                            <!-- 
                            contentフィールドを出力
                            truncatecharsで出力する文字数を50文字以内に制限
                            -->
                            {{record.content|truncatechars:50}}
                        </span>
                        
                    </h3>
                </a>
                <!-- 投稿日時とカテゴリ -->
                <p class="post-meta">
                    <!-- ページの最上位にリンクする -->
                    <a href="#">Django's Blog</a>
                    <!-- posted_atフィールドを出力 -->
                    {{record.posted_at}}に投稿/カテゴリ：
                    <!-- categoryフィールドを出力 -->
                    {{record.category}}</p>
            </div>
            <hr>
            {% endfor %}
            <!-- forによる繰り返しはここまで -->
            
            <!-- Pager-->
            <!-- ページネイション組み込み -->
            {% include "pagination.html" %}
        </div>
    </div>
</div>
<!-- Divider -->
<hr class="my-4" />
{% endblock %}
<!-- Footer-->
<!-- フッター以下はベーステンプレート設定済みなので削除 -->

blog/templates/index.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!-- 静的ファイルのURLを生成するstaticha
個々のページで読み込むことが必要-->
{% load static %}

<!-- ヘッダー情報のページタイトルは
ベーステンプレートを利用するページで設定する-->
{% block title %}Django's Blog{% endblock %}


<!-- Page Header-->
{% block header %}
<!-- ページヘッダーを設定（ドキュメントの構造に合わせてインデント） -->
<!-- ベーステンプレートを利用するページで設定する -->
<header class="masthead" style="background-image: url('{% static 'assets/img/home-bg.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <!-- ヘッダーの大見出し（タイトル）を変更 -->
                    <h1>Django's Blog</h1>
                    <!-- サブタイトルを変更 -->
                    <span class="subheading">A Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

<!-- Main Content-->
{% block contents %}
<!-- ページのコンテンツを設定（ドキュメントの構造に合わせてインデント） -->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- 
            全レコードが格納されたorderby_recordsから
            レコードを1件ずつrecordに取り出す
            -->
            {% for record in orderby_records %}
            <!-- Post preview-->
            <div class="post-preview">
                <!--
                urlでURLパターン'blog-detail/記事のid/'を生成し、
                詳細尾エージへのリンクを設定
                -->
                <a href="{% url 'blog:blog_detail' record.pk %}">
                    <!-- 記事のタイトル -->
                    <h2 class="post-title">
                        <!-- titleフィールドを出力 -->
                        {{record.title}}
                    </h2>
                    <!-- 投稿記事本文 -->
                    <h3 class="post-subtitle">
                        <!-- サブタイトルの文字サイズを16ptにする -->
                        <span style="font-size: 16pt;">

                            <!-- 
                            contentフィールドを出力
                            truncatecharsで出力する文字数を50文字以内に制限
                            -->
                            {{record.content|truncatechars:50}}
                        </span>
                        
                    </h3>
                </a>
                <!-- 投稿日時とカテゴリ -->
                <p class="post-meta">
                    <!-- ページの最上位にリンクする -->
                    <a href="#">Django's Blog</a>
                    <!-- posted_atフィールドを出力 -->
                    {{record.posted_at}}に投稿/カテゴリ：
                    <!-- categoryフィールドを出力 -->
                    {{record.category}}</p>
            </div>
            <hr>
            {% endfor %}
            <!-- forによる繰り返しはここまで -->
            
            <!-- Pager-->
            <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
        </div>
    </div>
</div>
<!-- Divider -->
<hr class="my-4" />
{% endblock %}
<!-- Footer-->
<!-- フッター以下はベーステンプレート設定済みなので削除 -->

blog/templates/music_list.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!-- 静的ファイルのURLを生成するstaticha
個々のページで読み込むことが必要-->
{% load static %}

<!-- ヘッダー情報のページタイトルは
ベーステンプレートを利用するページで設定する-->
{% block title %}Django's Blog - Music{% endblock %}


<!-- Page Header-->
{% block header %}
<!-- ページヘッダーを設定（ドキュメントの構造に合わせてインデント） -->
<!-- ベーステンプレートを利用するページで設定する -->
<header class="masthead" style="background-image: url('{% static 'assets/img/home-bg.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <!-- ヘッダーの大見出し（タイトル）を変更 -->
                    <h1>Django's Blog</h1>
                    <!-- サブタイトルを変更 -->
                    <span class="subheading">Musicカテゴリの記事一覧</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

<!-- Main Content-->
{% block contents %}
<!-- ページのコンテンツを設定（ドキュメントの構造に合わせてインデント） -->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- 
            Scienceレコードが格納されたscience_recordsから
            レコードを1件ずつrecordに取り出す
            -->
            {% for record in music_records %}
            <!-- Post preview-->
            <div class="post-preview">
                <!--
                urlでURLパターン'blog-detail/記事のid/'を生成し、
                詳細尾エージへのリンクを設定
                -->
                <a href="{% url 'blog:blog_detail' record.pk %}">
                    <!-- 記事のタイトル -->
                    <h2 class="post-title">
                        <!-- titleフィールドを出力 -->
                        {{record.title}}
                    </h2>
                    <!-- 投稿記事本文 -->
                    <h3 class="post-subtitle">
                        <!-- サブタイトルの文字サイズを16ptにする -->
                        <span style="font-size: 16pt;">

                            <!-- 
                            contentフィールドを出力
                            truncatecharsで出力する文字数を50文字以内に制限
                            -->
                            {{record.content|truncatechars:50}}
                        </span>
                        
                    </h3>
                </a>
                <!-- 投稿日時とカテゴリ -->
                <p class="post-meta">
                    <!-- ページの最上位にリンクする -->
                    <a href="#">Django's Blog</a>
                    <!-- posted_atフィールドを出力 -->
                    {{record.posted_at}}に投稿/カテゴリ：
                    <!-- categoryフィールドを出力 -->
                    {{record.category}}</p>
            </div>
            <hr>
            {% endfor %}
            <!-- forによる繰り返しはここまで -->
            
            <!-- Pager-->
            <!-- ページネイション組み込み -->
            {% include "pagination.html" %}
        </div>
    </div>
</div>
<!-- Divider -->
<hr class="my-4" />
{% endblock %}
<!-- Footer-->
<!-- フッター以下はベーステンプレート設定済みなので削除 -->

blog/templates/post.html
<!-- ベーステンプレートを適用 -->
{% extends 'base.html' %}

<!-- 
静的ファイルのURLを生成するstaticタグのロードは
個々のページで行うことが必要
-->
{% load static %}

<!-- ヘッダー情報のページタイトルは
ベーステンプレートを利用するページで設定する-->

{% block title %}Django's Blog{% endblock %}

<!-- 
<!DOCUTYPE html>以下、<head>~</head>までベーステンプレートで設定済なので削除
-->

<body>
        <!-- Navigation -->
        <!-- <body>,<nav>~</nav>はベーステンプレートで設定済なので削除 -->
        
        <!-- Page Header-->
        <!-- ページのヘッダーはベーステンプレートを使用するページで設定する -->
        {% block header %}

        
        <!-- ヘッダーの背景イメージのリンク先はurl()の引数をstaticタグに書き換え -->
        <header class="masthead" style="background-image: url('{% static 'assets/img/home-bg.jpg' %}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="post-heading">
                            <!-- 
                            投稿記事のタイトル
                            <h1>タグの要素を書き換える
                            レコードをobjectで参照し、titleフィールドの値を出力
                            -->
                            <h1>{{object.title}}</h1>
                            <!-- サブタイトル
                            <h2>の要素を書き換える
                            レコードをobjectで参照し、contentフィールドの値を30文字以内で出力
                            -->
                            <h2 class="subheading">{{object.content|truncatechars:30}}</h2>
                            <span class="meta">
                            <!-- 投稿日時とカテゴリ -->
                            <a href="{% url 'blog:index' %}">Django's Blog</a>
                            <!-- 投稿日時を出力としてposted_atフィールドを出力 -->
                            {{object.posted_at}}に投稿/カテゴリ：
                            <!-- categoryフィールドを出力 -->
                            {{object.category}}</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}

        <!-- Post Content-->
        {% block contents %}
        <article>
            <div class="container">
                <div class="row">
                    <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
                        <p>{{object.content}}</p>
                    </div>
                </div>
            </div>
        </article>
        <hr>
        {% endblock %}
        <!-- Footer-->
        <!-- フッター以下はベーステンプレートで設定済なので削除 -->